### ISSUE TITLE
Also modifies icon sizes

### ISSUE THREAD

**Issue by bendigi** [glyphish/color-changer#13]
I'm not sure why this hasn't been reported earlier as it is quite obvious that icons are modified. 
For instance, when you drag a 56x56 icon into the colour changer it also modifies it's size to 14x14.

I have tried to replace existing path and saving to a new directory both lead to the same experience.

**Comment by ruddfawcett** [comment]
Thanks for the report. This should have been fixed (and was reported - #2, #3, #12), but there still seem to be issues.  I'll look into this when I can.

**Comment by jpwain** [comment]
Thanks @ruddfawcett! Let me know what you find.

**Comment by bendigi** [comment]
Deleted all versions and double checked with the latest release and it's fine now. 
I'm not sure if this was a glitch or somehow an older build was being invoked.

**Comment by ruddfawcett** [comment]
@bendigi :+1:

**Comment by starfishci** [comment]
I'm still seeing this issue of icon resizing, with Beta 1, 2 and 3.

**Comment by ruddfawcett** [comment]
@starfishci what type of screen are you using?  Are you using an external display, or a built in?  If the latter, which type of computer/screen resolution?

**Comment by starfishci** [comment]
Thanks for the snappy response. I'm on a MacBook Pro Retina 15-inch, late-2013. No external monitors

**Comment by ruddfawcett** [comment]
@starfishci thanks - are you having problems with all of the icon sizes?  Or just the @3xs?

**Comment by starfishci** [comment]
It's all of them :( 

I first tried dragging groups of three; then each one individually. Either approach results in change of icon size: 

28x14 icon is re-colored and resized to 14x7
56x28 icon is re-colored and resized to 28x14
84x42 icon is re-colored and resized to 42x21

I've currently down-graded to Glyphish Color Changer v1.0 but found the same problem with v1.3
